VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClsVattu"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' Kieu vat tu
Public TendoId As String
Public MaSo As Long             ' Ma vat tu
Public MaPhanLoai As Long       ' ma phan loai
Public sohieu As String         ' So hieu vat tu
Public TenVattu As String       ' Ten vat tu
Public DonVi As String          ' Don vi tinh
Public TonMin As Double         ' Luong ton toi thieu (=0 neu bo qua)
Public TonMax As Double         ' Luong ton toi da (=0 neu bo qua)
Public GiaHT As Double
Public Dvt2 As Integer
Public DonVi2 As String
Public TyLeQD As Double
Public GhiChu As String
Public VAT As Integer
Public GiaBan1 As Double
Public GiaBan2 As Double
Public GiaBan3 As Double
Public CK As Double
Public ThueNK As Double
'======================================================================================
' Thu tuc khoi tao object tu ma so vat tu
' mvt:  Ma so vat tu can tham chieu
'       =0 neu vat tu moi
' ClsVattu.cls
' ClsVattu.cls
Public Function CreateFromMaSo(mvt As Long) As ClsVattu
    Dim rs_vattu As Object
    Dim vt As New ClsVattu

    If mvt > 0 Then
        Set rs_vattu = DBKetoan.OpenRecordset("SELECT Vattu.*" _
                                            & " FROM Vattu" _
                                            & " WHERE Vattu.MaSo=" + CStr(mvt), dbOpenSnapshot)
        
        If rs_vattu.recordCount > 0 Then
            ' Gán d? li?u vào object vt (dùng Me ho?c tr?c ti?p)
            vt.MaSo = rs_vattu!MaSo
            vt.MaPhanLoai = rs_vattu!MaPhanLoai
            vt.sohieu = rs_vattu!sohieu
            vt.TenVattu = rs_vattu!TenVattu
            vt.DonVi = rs_vattu!DonVi
            vt.TonMin = rs_vattu!TonMin
            vt.TonMax = rs_vattu!TonMax
            vt.GiaHT = rs_vattu!GiaHT
            
            If IsNull(rs_vattu!Dvt2) Then
                vt.Dvt2 = 0
            Else
                vt.Dvt2 = rs_vattu!Dvt2
            End If
            
            vt.DonVi2 = rs_vattu!DonVi2
            
            If IsNull(rs_vattu!TyLeQD) Then
                vt.TyLeQD = 0
            Else
                vt.TyLeQD = rs_vattu!TyLeQD
            End If
            
            vt.GhiChu = rs_vattu!GhiChu
            
            If IsNull(rs_vattu!VAT) Then
                vt.VAT = 0
            Else
                vt.VAT = rs_vattu!VAT
            End If
            
            vt.GiaBan1 = rs_vattu!GiaBan1
            vt.GiaBan2 = rs_vattu!GiaBan2
            vt.GiaBan3 = rs_vattu!GiaBan3
            vt.CK = rs_vattu!CK
        End If
        
        rs_vattu.Close
        Set rs_vattu = Nothing
    End If
    
    ' Tr? v? object dã du?c gán d? li?u
    Set CreateFromMaSo = vt
End Function
Public Sub InitVattuMaSo(mvt As Long)
    Dim rs_vattu As Object

    If mvt > 0 Then
        Set rs_vattu = DBKetoan.OpenRecordset("SELECT Vattu.*" _
                                            & " FROM Vattu" _
                                            & " WHERE Vattu.MaSo=" + CStr(mvt), dbOpenSnapshot)
        If rs_vattu.recordCount = 0 Then GoTo iv
        If rs_vattu!TendoId <> Null Then
            TendoId = rs_vattu!TendoId
            If TendoId <> "..." And TendoId <> "" Then
                FrmVattu.Label1.Caption = TendoId
                FrmVattu.Label1.Visible = True
            Else
                FrmVattu.Label1.Visible = False
            End If
        End If
        MaSo = rs_vattu!MaSo
        MaPhanLoai = rs_vattu!MaPhanLoai
        sohieu = rs_vattu!sohieu
        TenVattu = rs_vattu!TenVattu
        DonVi = rs_vattu!DonVi
        TonMin = IIf(IsNull(rs_vattu!TonMin), 0, rs_vattu!TonMin)
        TonMax = IIf(IsNull(rs_vattu!TonMax), 0, rs_vattu!TonMax)
        GiaHT = IIf(IsNull(rs_vattu!GiaHT), 0, rs_vattu!GiaHT)
        If IsNull(rs_vattu!Dvt2) Then
            Dvt2 = 0
        Else
            Dvt2 = rs_vattu!Dvt2
        End If
        DonVi2 = IIf(IsNull(rs_vattu!DonVi2), 0, rs_vattu!DonVi2)
        If IsNull(rs_vattu!TyLeQD) Then
            TyLeQD = 0
        Else
            TyLeQD = rs_vattu!TyLeQD
        End If
        GhiChu = IIf(IsNull(rs_vattu!GhiChu), 0, rs_vattu!GhiChu)
        If IsNull(rs_vattu!VAT) Then
            VAT = 0
        Else
            VAT = rs_vattu!VAT
        End If
        GiaBan1 = IIf(IsNull(rs_vattu!GiaBan1), 0, rs_vattu!GiaBan1)
        GiaBan2 = IIf(IsNull(rs_vattu!GiaBan2), 0, rs_vattu!GiaBan2)
        GiaBan3 = IIf(IsNull(rs_vattu!GiaBan3), 0, rs_vattu!GiaBan3)
        CK = IIf(IsNull(rs_vattu!CK), 0, rs_vattu!CK)
        'ThueNK = rs_vattu!ThueNK
        rs_vattu.Close
        Set rs_vattu = Nothing
    Else
iv:
        MaSo = 0
        MaPhanLoai = 0
        sohieu = ""
        TenVattu = ""
        DonVi = ""
        TonMin = 0
        TonMax = 0
        GiaHT = 0
        Dvt2 = 0
        DonVi2 = "..."
        TyLeQD = 0
        GhiChu = "..."
        VAT = 0
        GiaBan1 = 0
        GiaBan2 = 0
        GiaBan3 = 0
        CK = 0
        ThueNK = 0
    End If
End Sub
'==========================================================================
' Thu tuc khoi tao object tu so hieu vat tu
' mvt:  So hieu vat tu can tham chieu
'==========================================================================
Public Function InitVattuSohieu(shvt As String) As String
    Dim SQL As String
    
    SQL = "SELECT DISTINCTROW MaSo AS F1 FROM Vattu WHERE Sohieu='" + shvt + "'"
    
    InitVattuMaSo SelectSQL(SQL)
    InitVattuSohieu = TenVattu
End Function
'==========================================================================
' Thu tuc dang ky vat tu
'==========================================================================
Public Function GhiVattu() As Integer
    Dim SQL As String
        
   SQL = "INSERT INTO Vattu (MaPhanLoai,SoHieu,TenVattu,DonVi,TonMin,TonMax,GiaHT,Dvt2,DonVi2,TyLeQD,GhiChu,VAT,GiaBan1,GiaBan2,GiaBan3,CK,ThueNK,TendokhoInventory) VALUES (" _
        & CStr(MaPhanLoai) _
        & ",'" & sohieu & "'" _
        & ",'" & TenVattu & "'" _
        & ",'" & DonVi & "'" _
        & "," & DoiDau(TonMin) _
        & "," & DoiDau(TonMax) _
        & "," & DoiDau(RoundMoney(GiaHT)) _
        & "," & CStr(Dvt2) _
        & ",'" & DonVi2 & "'" _
        & "," & DoiDau(CDbl(TyLeQD)) _
        & ",'" & GhiChu & "'" _
        & "," & CStr(VAT) _
        & "," & DoiDau(GiaBan1) _
        & "," & DoiDau(GiaBan2) _
        & "," & DoiDau(GiaBan3) _
        & "," & DoiDau(CK) _
        & "," & DoiDau(ThueNK) _
        & "," & IIf(FrmVattu.chkTonKho.Value = 1, 1, 0) _
        & ")"
    If ExecuteSQL5(SQL) <> 0 Then
        GhiVattu = -1
    Else
        GhiVattu = 0
        MaSo = Lng_MaxValue("MaSo", "Vattu")
    End If
End Function
'==========================================================================
' Thu tuc tra ve TRUE neu vat tu da co phat sinh
'==========================================================================
Public Function VTCoDuLieu() As Boolean
    Dim SQL As String
    
    SQL = "SELECT DISTINCTROW Count(MaSo) AS F1 FROM Chungtu WHERE MaVattu=" + CStr(MaSo)
    VTCoDuLieu = SelectSQL(SQL) > 0
    If Not VTCoDuLieu Then
        SQL = "SELECT DISTINCTROW Count(MaSo) AS F1 FROM DinhMuc WHERE MaNVL=" + CStr(MaSo)
        VTCoDuLieu = SelectSQL(SQL) > 0
    End If
End Function
'==========================================================================
' Cap nhat thong tin ve vat tu
'==========================================================================
Public Function SuaVT() As Integer
    Dim SQL As String
    SQL = "UPDATE Vattu SET MaPhanLoai=" + CStr(MaPhanLoai) + ",SoHieu='" + sohieu + "',TenVattu='" + TenVattu + "',DonVi='" + DonVi + "',TonMin=" _
        + DoiDau(TonMin) + ",TonMax=" + DoiDau(TonMax) + ",GiaHT=" + DoiDau(RoundMoney(GiaHT)) + ",Dvt2=" + CStr(Dvt2) + ",DonVi2='" _
        + DonVi2 + "',TyLeQD=" + DoiDau(CDbl(TyLeQD)) + ",GhiChu='" + GhiChu + "',VAT=" + CStr(VAT) + ",GiaBan1=" + DoiDau(GiaBan1) _
        + ",GiaBan2=" + DoiDau(GiaBan2) + ",GiaBan3=" + DoiDau(GiaBan3) + ",CK=" + DoiDau(CK) + ",ThueNK=" + DoiDau(ThueNK) + " WHERE MaSo=" + CStr(MaSo)
    If ExecuteSQL5(SQL) <> 0 Then
        SuaVT = -1
    Else
        SuaVT = 0
    End If
End Function
'==========================================================================
' Thu tuc xoa mot vat tu
'==========================================================================
Public Function XoaVT() As Integer
    Dim i As Integer, SQL As String
    
    If VTCoDuLieu() Then
        XoaVT = -1
    Else
'        sql = "DELETE * FROM DVTVattu WHERE MaVattu=" + CStr(MaSo)
'        ExecuteSQL5 sql
    For i = 1 To 12
            SQL = SQL + " or Luong_Nhap_" + CStr(i) + "<>0 or Tien_Nhap_" + CStr(i) + "<>0 "
        Next
          SQL = "select count(*) as f1 FROM TonKho WHERE MaVattu=" + CStr(MaSo) + " AND (Luong_0<>0 or  Tien_0<>0) "
         
        If SelectSQL(SQL) <= 0 Then
        SQL = "DELETE FROM TonKho WHERE MaVattu=" + CStr(MaSo) + " AND (Luong_0=0 AND Tien_0=0) "
        For i = 1 To 12
            SQL = SQL + " AND Luong_Nhap_" + CStr(i) + "=0 AND Tien_Nhap_" + CStr(i) + "=0 "
        Next
        ExecuteSQL5 SQL
        
        If ExecuteSQL5("DELETE FROM Vattu WHERE MaSo=" + CStr(MaSo)) = 0 Then
            XoaVT = 0
        Else
            XoaVT = -1
        End If
        Else
        XoaVT = -1
        End If
        
    End If
End Function

Public Function XoaDVT(m As Long) As Boolean
    XoaDVT = False
    If SelectSQL("SELECT MaCT AS F1 FROM ChungTu WHERE MaVattu=" + CStr(MaSo) + " AND DVT=" + CStr(m)) = 0 Then
        If ExecuteSQL5("DELETE * FROM DVTVattu WHERE MaSo=" + CStr(m)) = 0 Then XoaDVT = True
    End If
End Function

Public Sub KTraDVT2()
    Dim dv2 As Long
    
    dv2 = SelectSQL("SELECT Top 1 MaSo AS F1 FROM DVTVattu WHERE MaVattu=" + CStr(MaSo))
    ExecuteSQL5 "UPDATE Vattu SET Dvt2=" + IIf(dv2 > 0, "1", "0") + " WHERE MaSo=" + CStr(MaSo)
End Sub

Public Function SoChietKhau(sops As Double) As Double
    SoChietKhau = RoundMoney(sops * CK / 100)
End Function
